import { TabWidget, ListView } from "std-widgets.slint";

AppWindow := Window {
    property <[string]> news;

    TabWidget {
        Tab {
            title: "News";
            ListView {
                for article in news : Text {
                    text: article;
                }
            }
        }
        Tab {
            title: "Settings";
        }
        Tab {
            title: "About";
            Text {
                text: "GPLv3 Licensed | © 2022 Manuel Quarneti";
            }
        }
    }
}
